GET http://localhost:8080/api/groups

###
GET http://localhost:8080/api/groups/639977d10186a8aa15db34a4

###
POST http://localhost:8080/api/groups
Content-Type: application/json

{
  "name": "Test Group",
  "weeklyRations": "4",
}