GET http://localhost:8080/api/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZmRhYWQxYTlhZjhmNzFlYzdjMDAzYSIsImlhdCI6MTY3NzU5NDA3MX0.rWmSLw4Tvj06RSmhL22Q-6P851UqUYWK_XDgvbsl9yI

###
GET http://localhost:8080/api/groups/63fefee32cfc5ea9d479a36c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZmRhYWQxYTlhZjhmNzFlYzdjMDAzYSIsImlhdCI6MTY3NzU5NDA3MX0.rWmSLw4Tvj06RSmhL22Q-6P851UqUYWK_XDgvbsl9yI

###
POST http://localhost:8080/api/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZmRhYWQxYTlhZjhmNzFlYzdjMDAzYSIsImlhdCI6MTY3NzU5NDA3MX0.rWmSLw4Tvj06RSmhL22Q-6P851UqUYWK_XDgvbsl9yI

{
  "name": "Test Group w/ Token",
  "weeklyRations": 4
}

###
PUT http://localhost:8080/api/groups/63f61eec3ae7a8e9eaba1eaf
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZmRhYWQxYTlhZjhmNzFlYzdjMDAzYSIsImlhdCI6MTY3NzU5NDA3MX0.rWmSLw4Tvj06RSmhL22Q-6P851UqUYWK_XDgvbsl9yI

{
  "name": "Test Group",
  "weeklyRations": 4
}

###
DELETE http://localhost:8080/api/groups/63fefc76648bba842db7815b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZmRhYWQxYTlhZjhmNzFlYzdjMDAzYSIsImlhdCI6MTY3NzU5NDA3MX0.rWmSLw4Tvj06RSmhL22Q-6P851UqUYWK_XDgvbsl9yI
