GET http://localhost:8080/api/plans

###
GET http://localhost:8080/api/plans/63f71a011077ccaaec7a9ed8

###
POST http://localhost:8080/api/plans
Content-Type: application/json

{
  "name": "Test Plan",
  "lunch": [
    "Test Meal", 
    "Test Meal",
    "Test Meal", 
    "Test Meal",
    "Test Meal", 
    "Test Meal",
    "Test Meal" 
  ],
  "dinner": [
    "Test Meal", 
    "Test Meal",
    "Test Meal", 
    "Test Meal",
    "Test Meal", 
    "Test Meal",
    "Test Meal"
  ],
  "userId": "63f1b8f10ce699c3db841c70"
}

###
PUT http://localhost:8080/api/plans/63f71a011077ccaaec7a9ed8
Content-Type: application/json

{
  "name": "Modified Test Plan",
  "lunch": [
    "Test Meal 2", 
    "Test Meal 2",
    "Test Meal 2", 
    "Test Meal 2",
    "Test Meal 2", 
    "Test Meal 2",
    "Test Meal 2" 
  ],
  "dinner": [
    "Test Meal", 
    "Test Meal",
    "Test Meal", 
    "Test Meal",
    "Test Meal", 
    "Test Meal",
    "Test Meal"
  ],
  "userId": "63f1b8f10ce699c3db841c70"
}

###
DELETE http://localhost:8080/api/plans/63a07365f987df5ed7dd2e41