GET http://localhost:8080/api/plans

###
GET http://localhost:8080/api/plans/63a07365f987df5ed7dd2e41

###
POST http://localhost:8080/api/plans
Content-Type: application/json

{
  "name": "Test Plan",
  "lunch": [
    "Tortilla de patatas", 
    "Pruebe con huevos fritos",
    "Fajitas tortillas", 
    "Tortilla de calabacin",
    "Tortilla de patatas", 
    "Pruebe con huevos fritos",
    "Fajitas tortillas" 
  ],
  "dinner": [
    "Tortilla de patatas", 
    "Pruebe con huevos fritos",
    "Fajitas tortillas", 
    "Tortilla de calabacin",
    "Tortilla de patatas", 
    "Pruebe con huevos fritos",
    "Fajitas tortillas"
    ]
}

###
PUT http://localhost:8080/api/plans/63a07365f987df5ed7dd2e41
Content-Type: application/json

{
  "name": "Modified Test Plan",
  "lunch": [
    "Tortilla de patatas", 
    "Pruebe con huevos fritos",
    "Fajitas tortillas", 
    "Tortilla de calabacin",
    "Tortilla de patatas", 
    "Pruebe con huevos fritos",
    "Fajitas tortillas" 
  ],
  "dinner": [
    "Tortilla de patatas", 
    "Pruebe con huevos fritos",
    "Fajitas tortillas", 
    "Tortilla de calabacin",
    "Tortilla de patatas", 
    "Pruebe con huevos fritos",
    "Fajitas tortillas"
    ]
}

###
DELETE http://localhost:8080/api/plans/63a070290aa4dda29478c2ed